# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 14:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('AG', 'Agriculture'), ('BU', 'Business'), ('CO', 'Commercial'), ('GO', 'Government'), ('GP', 'Government purposes'), ('IN', 'Industrial'), ('MI', 'Mining'), ('MU', 'Multi-use (public, residential, commercial)'), ('RC', 'Recreational'), ('RE', 'Residential'), ('TR', 'Transport'), ('UN', 'Unknown')], help_text='Choose all types of development that form part of the application.', max_length=2)),
                ('footprint', django.contrib.gis.db.models.fields.PolygonField(help_text='Should be a .geojson file.', srid=4326)),
                ('geo_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('applicant', models.CharField(blank=True, help_text='The name of the development company who applied for the permit?', max_length=100, null=True)),
                ('application_title', models.CharField(blank=True, help_text="Should describe what the development is, e.g. 'Establishment of the Northern Golf Course Estate, Johannesburg Gauteng'.", max_length=500, null=True)),
                ('activity_description', models.TextField(blank=True, help_text="Provides more detail on what the development will entail, e.g. 'The development proposal will comprise of the following: Residential, internal roads, and access control.'", null=True)),
                ('case_officer', models.CharField(blank=True, help_text='The name of the case officer dealing with the application.', max_length=100, null=True)),
                ('environmental_consultancy', models.CharField(blank=True, help_text='The name of the consultancy who performed the EIA', max_length=100, null=True)),
                ('environmental_assessment_practitioner', models.CharField(blank=True, help_text='The name of the staff member in the above consultancy.', max_length=100, null=True)),
                ('location_description', models.TextField(blank=True, help_text='A description of the locality of the development.', null=True)),
                ('unique_id', models.CharField(blank=True, help_text="This is SANBI's ID number for this development.", max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('type', models.CharField(blank=True, choices=[('HE', 'Hectares'), ('RE', 'Research'), ('RH', 'Rehabilitation'), ('FI', 'Financial compensation')], max_length=2, null=True)),
                ('duration', models.CharField(choices=[('PE', 'Perpetuity'), ('US', 'Unspecified'), ('UN', 'Unknown'), ('LT', '< 20 years'), ('TF', 'Between 20 and 50 years'), ('HC', '> 50 years')], max_length=2)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Development')),
            ],
        ),
        migrations.CreateModel(
            name='OffsetImplementationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_hectares', models.IntegerField(blank=True, help_text='The area in hectares associated with this permit.', null=True)),
                ('date_issued', models.DateField(blank=True, help_text='The date this permit was issued.', null=True)),
                ('reference_no', models.CharField(blank=True, help_text='The reference number for the permit.', max_length=200, null=True)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Development')),
            ],
        ),
        migrations.CreateModel(
            name='PermitName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. Department of Water Affairs.', max_length=100)),
                ('authority', models.CharField(help_text='E.g. Water Use License (WULA).', max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='permitname',
            unique_together=set([('name', 'authority')]),
        ),
        migrations.AddField(
            model_name='permit',
            name='permit_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PermitName'),
        ),
        migrations.AddField(
            model_name='offset',
            name='implementation_times',
            field=models.ManyToManyField(to='core.OffsetImplementationTime'),
        ),
        migrations.AddField(
            model_name='development',
            name='permits',
            field=models.ManyToManyField(help_text='May be one of several, linked to the Permit model. Do not select any options if there is no information about the permit.', through='core.Permit', to='core.PermitName'),
        ),
    ]
