# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 11:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('type', models.CharField(choices=[('AG', 'Agriculture'), ('BU', 'Business'), ('GO', 'Government'), ('GP', 'Government purposes'), ('IN', 'Industrial'), ('MI', 'Mining'), ('MU', 'Multi-use (public, residential, commercial)'), ('RC', 'Recreational'), ('RE', 'Residential'), ('TR', 'Transport'), ('UN', 'Unknown')], max_length=2)),
                ('implementation_nature', models.CharField(choices=[('ST', 'Staggered'), ('OO', 'Once-off'), ('UN', 'Unknown'), ('US', 'Unspecific')], max_length=2)),
                ('footprint', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Offset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('type', models.CharField(blank=True, choices=[('HE', 'Hectares'), ('RE', 'Research'), ('RH', 'Rehabilitation'), ('FI', 'Financial compensation')], max_length=2, null=True)),
                ('duration', models.CharField(choices=[('PE', 'Perpetuity'), ('US', 'Unspecified'), ('UN', 'Unknown'), ('LT', '< 20 years'), ('TF', 'Between 20 and 50 years'), ('HC', '> 50 years')], max_length=2)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Development')),
            ],
        ),
        migrations.CreateModel(
            name='OffsetImplementationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='offset',
            name='implementation_times',
            field=models.ManyToManyField(to='core.OffsetImplementationTime'),
        ),
        migrations.AddField(
            model_name='development',
            name='permits',
            field=models.ManyToManyField(to='core.Permit'),
        ),
    ]
