# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='development',
            name='implementation_nature',
        ),
        migrations.AlterField(
            model_name='development',
            name='year',
            field=models.IntegerField(),
        ),
    ]
