# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permitname',
            name='authority',
            field=models.CharField(help_text='Name of the authority who issues the permit - e.g. Department of Water Affairs.', max_length=100),
        ),
        migrations.AlterField(
            model_name='permitname',
            name='name',
            field=models.CharField(help_text='Name of the permit - e.g. Water Use License (WULA).', max_length=100),
        ),
    ]
