# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 09:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171106_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='footprint',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(help_text='Should be a .geojson file.', srid=4326),
        ),
        migrations.AlterField(
            model_name='offset',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
