# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171213_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offset',
            name='offset_met',
            field=models.CharField(choices=[('ME', 'Yes, this offset has been met'), ('LA', 'No, this offset has not been met and the time has lapsed, it is outstanding.'), ('IP', 'No, this offset has not yet been met but the development is still in progress.'), ('NU', 'No, this offset has not been met for reasons unknown.'), ('NO', 'No, this offset has not been met because there is no offset area available.'), ('UN', "We don't know if this offset has been met or not.")], help_text='The status of the offset requirement (whether it has been met or not).', max_length=1),
        ),
    ]
