# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170714_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permit',
            old_name='permit',
            new_name='name',
        ),
    ]
