# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170714_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offsetimplementationtime',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
