# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171106_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='development',
            name='case_officer',
        ),
        migrations.AddField(
            model_name='permit',
            name='case_officer',
            field=models.CharField(blank=True, help_text='The name of the case officer dealing with the permit.', max_length=100, null=True),
        ),
    ]
