# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171214_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biodiversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Ecosystem'), ('T', 'Threatened or protected species populations/individuals')], max_length=1)),
                ('name', models.CharField(blank=True, help_text='The name of the ecosystem or protected species.', max_length=200, null=True)),
                ('size', models.IntegerField(blank=True, help_text='This is the area in hectares relevant to this trigger (e.g. 20 ha of pristine renosterveld will be destroyed).', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='biodiversityloss',
            name='id',
        ),
        migrations.RemoveField(
            model_name='biodiversityloss',
            name='name',
        ),
        migrations.RemoveField(
            model_name='biodiversityloss',
            name='size',
        ),
        migrations.RemoveField(
            model_name='biodiversityloss',
            name='type',
        ),
        migrations.CreateModel(
            name='BiodiversityGain',
            fields=[
                ('biodiversity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Biodiversity')),
                ('offset', models.ForeignKey(help_text="The relevant offset, should only link to offsets of type 'hectares'.", on_delete=django.db.models.deletion.CASCADE, to='core.Offset')),
            ],
            bases=('core.biodiversity',),
        ),
        migrations.AddField(
            model_name='biodiversityloss',
            name='biodiversity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Biodiversity'),
            preserve_default=False,
        ),
    ]
