# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 11:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171113_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='footprint',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Should be a .geojson file.', null=True, srid=4326),
        ),
    ]
