# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 11:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171113_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='geo_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
