# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 08:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170814_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
