# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 16:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_development_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='offset',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
