# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171113_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='development',
            old_name='unique_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='development',
            old_name='applicant',
            new_name='developer',
        ),
        migrations.RemoveField(
            model_name='development',
            name='permits',
        ),
    ]
