# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_offset_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offsetimplementationtime',
            old_name='time',
            new_name='name',
        ),
    ]
