# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170824_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='development',
            old_name='info',
            new_name='geo_info',
        ),
        migrations.AlterField(
            model_name='development',
            name='type',
            field=models.CharField(choices=[('AG', 'Agriculture'), ('BU', 'Business'), ('CO', 'Commercial'), ('GO', 'Government'), ('GP', 'Government purposes'), ('IN', 'Industrial'), ('MI', 'Mining'), ('MU', 'Multi-use (public, residential, commercial)'), ('RC', 'Recreational'), ('RE', 'Residential'), ('TR', 'Transport'), ('UN', 'Unknown')], help_text='Choose all types of development that form part of the application.', max_length=2),
        ),
    ]
