# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171211_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='offset_requirement_stipulated',
            field=models.CharField(choices=[('Y', 'Yes'), ('D', "No, the offset hasn't been determined"), ('P', 'No, not publicised')], default='Y', help_text='Choose all types of development that form part of the application.', max_length=2),
            preserve_default=False,
        ),
    ]
