# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_permit_offset_requirement_stipulated'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffsetTriggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_trigger', models.CharField(choices=[('E', 'Ecosystem'), ('TSP', 'Threatened or protected species')], max_length=1)),
                ('name', models.CharField(blank=True, help_text='The name of the ecosystem or protected species.', max_length=200, null=True)),
                ('size', models.IntegerField(blank=True, help_text='This is the actual amount of space the development is taking up of this ecosystem.', null=True)),
                ('required_offset_size', models.IntegerField(blank=True, help_text='The condition of the authorisation, specified in hectares.', null=True)),
            ],
        ),
    ]
