# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_offsettriggers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OffsetTriggers',
            new_name='OffsetTrigger',
        ),
    ]
