# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171212_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offset',
            name='development',
        ),
        migrations.AddField(
            model_name='offset',
            name='permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Permit'),
        ),
        migrations.AddField(
            model_name='offsettrigger',
            name='offset_met',
            field=models.CharField(blank=True, choices=[('ME', 'Yes, this offset has been met'), ('LA', 'No, this offset has not been met and the time has lapsed, it is outstanding.'), ('IP', 'No, this offset has not yet been met but the development is still in progress.'), ('NU', 'No, this offset has not been met for reasons unknown.')], max_length=1, null=True),
        ),
    ]
