# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171212_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='area_hectares',
        ),
        migrations.AddField(
            model_name='development',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offsettrigger',
            name='required_offset_size',
            field=models.IntegerField(blank=True, help_text='The condition of the authorisation, specified in hectares (e.g. conserve 40 ha of pristine renosterveld in compensation)', null=True),
        ),
        migrations.AlterField(
            model_name='offsettrigger',
            name='size',
            field=models.IntegerField(blank=True, help_text='This is the area in hectares relevant to this trigger (e.g. 20 ha of pristine renosterveld will be destroyed).', null=True),
        ),
    ]
