# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171212_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='development',
            name='geo_info',
        ),
        migrations.AlterField(
            model_name='development',
            name='start_date',
            field=models.DateField(blank=True, help_text='The day on which development is due to start.', null=True),
        ),
    ]
