# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('RA', 'Ramsar Site'), ('WH', 'World Heritage Site'), ('NP', 'National Park'), ('BG', 'Botanical Garden')], max_length=2)),
                ('footprint', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
