# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatialbiodiversity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protectedarea',
            old_name='footprint',
            new_name='polygon',
        ),
        migrations.RemoveField(
            model_name='protectedarea',
            name='year',
        ),
        migrations.AddField(
            model_name='protectedarea',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
