# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geospatialbiodiversity', '0002_auto_20170714_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectedarea',
            name='type',
            field=models.CharField(choices=[('RA', 'Ramsar Site'), ('WH', 'World Heritage Site'), ('NP', 'National Park'), ('BG', 'Botanical Garden'), ('BG', 'Province')], max_length=2),
        ),
    ]
